#ifndef RT_MODULE_TEST_MACRO_H
#define RT_MODULE_TEST_MACRO_H

#define RT_THREAD_TEST
//#define RT_TIMER_TEST
//#define RT_SEM_TEST
//#define RT_MUTEX_TEST
//#define RT_EVENT_TEST
//#define RT_MAILBOX_TEST
//#define RT_MESSAGE_QUEUE_TEST
#define RT_SERIAL_DEVICE_TEST
//#define RT_PIN_DEVICE_TEST

#endif
